name: ubandbase
description: uband base widget
version: 0.2.2
author: "bing ma"
homepage:

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  rxdart: ^0.26.0
  # 提供 json 解析注解
  json_annotation: ^4.0.1
  # 状态管理框架
  flutter_bloc: ^7.0.0
  equatable: ^2.0.0
  # 提供 cookie 管理 https://pub.flutter-io.cn/packages/cookie_jar
  cookie_jar: ^2.0.0
  # 提供了基本 datatime 类型操作 https://pub.flutter-io.cn/packages/date_utils
  #date_utils:
  # dio是一个强大的Dart Http请求库 https://pub.flutter-io.cn/packages/dio
  dio: ^4.0.0
  # 本地化和国际化信息 https://pub.flutter-io.cn/packages/intl
  # intl:
  # 操作路径 https://pub.flutter-io.cn/packages/path
  path: ^1.8.0
  # 获取路径 https://pub.flutter-io.cn/packages/path_provider
  path_provider: ^2.0.1
  # event bus 事件库 https://pub.flutter-io.cn/packages/event_bus
  event_bus: ^2.0.0
  # 获取不同平台包信息 https://pub.flutter-io.cn/packages/package_info
  package_info: ^2.0.0
  # 支持不同平台下打开 URL https://pub.flutter-io.cn/packages/url_launcher
  url_launcher: ^6.0.12
  # 国际化 https://pub.flutter-io.cn/packages/flutter_i18n
  flutter_i18n: ^0.22.3
  # toast https://pub.flutter-io.cn/packages/fluttertoast
  fluttertoast: ^8.0.3
  # 日志打印 https://pub.flutter-io.cn/packages/logger
  logger: ^1.0.0
  # 模态对话框增强 https://pub.flutter-io.cn/packages/modal_bottom_sheet
  modal_bottom_sheet: ^2.0.0
  # 可拆叠列表的 Flutter 实现，支持粘性头部，可以与 Sliver 家族控件配合使用 https://pub.flutter-io.cn/packages/sticky_and_expandable_list
  #sticky_and_expandable_list: ^0.2.3
  # 可用于 sliver 的粘性头部组件
  #flutter_sticky_header: ^0.5.0
  # 本地临时存储
  shared_preferences: ^2.0.5
  image_picker: ^0.7.3
  camera: ^0.9.4+3

dev_dependencies:
  flutter_test:
    sdk: flutter

#dependency_overrides:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#  - images/a_dot_burr.jpeg
#  - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
